K: 20
TeammateEncoder_num_heads: 2
act_dim: 5
alpha: 0.001
batch_size: 2048
beta: 100
clip_value: 2
device: cuda
dt_activation_function: relu
dt_dropout: 0.1
dt_embed_dim: 64
dt_lr: 0.001
dt_train_steps: 1
dt_weight_decay: 0.0001
embed_dim: 64
env: stag_hunt
gama: 100
goal_dim: 75
lr: 0.01
max_ep_len: 201
model_save_path: models
n_head: 1
n_layer: 3
num_agents: 4
num_epochs: 500
save_dir: training_output/20241120_110459
save_interval: 10
state_dim: 75
test_interval: 25
train_data_path: data/PP4a_test_rtg.pt
type: PP4a
warmup_steps: 50
weight_decay: 0.0001
