K: 20
TeammateEncoder_num_heads: 2
act_dim: 5
alpha: 0.02
batch_size: 4096
beta: 100
clip_value: 1.5
device: cuda
dt_activation_function: relu
dt_dropout: 0.1
dt_embed_dim: 128
dt_lr: 0.001
dt_train_steps: 1
dt_weight_decay: 0.0001
embed_dim: 32
env: stag_hunt
gama: 100
goal_dim: 75
lr: 0.02
max_ep_len: 201
model_save_path: models
n_head: 1
n_layer: 3
num_agents: 4
num_epochs: 500
save_dir: training_output/20241116_115819
save_interval: 10
state_dim: 75
test_interval: 10
train_data_path: data/PP4a_episodes_datas.pt
type: PP4a
warmup_steps: 10000
