TeammateEncoder_num_heads: 4
alpha: 10
batch_size: 8192
beta: 100
clip_value: 1.0
device: !!python/object/apply:torch.device
- cuda
embed_dim: 32
env: stag_hunt
gama: 100
goal_dim: 75
lr: 0.01
model_save_path: models
num_agents: 4
num_epochs: 50
save_dir: training_output/20241111_010135
save_interval: 10
state_dim: 75
test_interval: 10
train_data_path: data/PP4a_episodes_datas.pt
type: PP4a
