K: 20
act_dim: 5
alpha: 0.0001
batch_size: 4096
beta: 100
clip_value: 2
device: cuda
dt_activation_function: relu
dt_dropout: 0.1
dt_embed_dim: 32
dt_lr: 0.0002
dt_weight_decay: 0.0001
env: stag_hunt
gama: 100
max_ep_len: 201
model_save_path: models
n_head: 1
n_layer: 2
num_agents: 4
num_epochs: 100
save_dir: training_output/20241121_152724
save_interval: 2
state_dim: 75
test_interval: 2
train_data_path: data/PP4a_episodes_datas_rtg.pt
type: PP4a
warmup_steps: 10
weight_decay: 1.0e-05
