env: stag_hunt
type: PP4a

device: cuda
batch_size: 4096
lr: 0.0001
weight_decay: 0.00001
alpha: 0.0001   # 预测r的MSE的权重
beta: 100   # MIE第一项的权重
gama: 100   # MIE第二项的权重
clip_value: 2
num_agents: 4

# train_model function
num_epochs: 500
save_interval: 20
model_save_path: models
test_interval: 20

# network
state_dim: 75
embed_dim: 64
TeammateEncoder_num_heads: 4
goal_dim: 75
act_dim: 5
max_ep_len: 201

# DT
dt_embed_dim: 64
K: 20
n_layer: 3
n_head: 1
dt_activation_function: relu
dt_dropout: 0.1
warmup_steps: 50
dt_weight_decay: 0.0001
dt_lr: 0.001
dt_train_steps: 1

# train_data_path: data/PP4a_episodes_datas.pt
train_data_path: data/PP4a_test_rtg.pt