env: stag_hunt
type: PP4a

device: cpu
batch_size: 512
lr: 0.01
alpha: 0.5   # 预测r的MSE的权重
beta: 100   # MIE第一项的权重
gama: 100   # MIE第二项的权重
clip_value: 1.0
save_interval: 5
num_agents: 4

# train_model function
num_epochs: 5000
save_interval: 10
model_save_path: models
test_interval: 10

# network
state_dim: 75
embed_dim: 32
TeammateEncoder_num_heads: 4
goal_dim: 75
act_dim: 5
max_ep_len: 201

# DT
dt_embed_dim: 128
K: 30
n_layer: 3
n_head: 1
dt_activation_function: relu
dt_dropout: 0.1
warmup_steps: 10000
dt_weight_decay: 0.0001
dt_lr: 0.001
dt_train_steps: 10

# train_data_path: data/PP4a_episodes_datas.pt
train_data_path: data/PP4a_test.pt