env: stag_hunt
type: PP4a

batch_size: 8192
lr: 0.01
alpha: 10
beta: 100
gama: 100
clip_value: 1.0
num_epochs: 5000
save_interval: 5
num_agents: 4

# train_model function
num_epochs: 50
save_interval: 10
model_save_path: models
test_interval: 10

# network
state_dim: 75
embed_dim: 32
TeammateEncoder_num_heads: 4
goal_dim: 75

train_data_path: data/PP4a_episodes_datas.pt
# train_data_path: data/PP4a_test.pt