K: 25
TeammateEncoder_num_heads: 2
act_dim: 6
alpha: 100
batch_size: 1024
beta: 100
clip_value: 2
device: cuda
dt_activation_function: relu
dt_dropout: 0.1
dt_embed_dim: 64
dt_train_steps: 1
dt_weight_decay: 0.0001
embed_dim: 128
env: lbf
gama: 100
goal_dim: 40
goal_steps: 3
lr: 0.01
max_ep_len: 51
model_save_path: models
n_head: 1
n_layer: 3
num_agents: 2
num_epochs: 100
save_dir: training_output/20241211_034628
save_interval: 2
sigma: 0.001
state_dim: 40
test_interval: 2
train_data_path: data/LBF_episodes_datas_rtg.pt
type: LBF
warmup_steps: 10
weight_decay: 1.0e-05
