K: 45
TeammateEncoder_num_heads: 4
act_dim: 6
alpha: 100
batch_size: 8192
beta: 100
clip_value: 2
device: cuda
dt_activation_function: relu
dt_dropout: 0.1
dt_embed_dim: 128
dt_lr: 0.01
dt_train_steps: 1
dt_weight_decay: 0.0001
embed_dim: 512
env: lbf
gama: 100
goal_dim: 2
goal_steps: 1
lr: 0.001
max_ep_len: 51
model_save_path: models
n_head: 1
n_layer: 3
num_agents: 2
num_epochs: 100
save_dir: training_output/20241203_062235
save_interval: 2
state_dim: 2
test_interval: 2
train_data_path: data/LBF_episodes_datas_rtg.pt
type: LBF
warmup_steps: 10
weight_decay: 1.0e-05
